# Example

In [1]:
import lda_eval_lib
import pandas as pd
import os

In [2]:
# Load a test file
package_path = os.path.dirname(lda_eval_lib.__file__)
data_path = os.path.join(package_path, 'test_text.pkl')
item1a = pd.read_pickle(data_path)
tokenized_text = item1a['text4LDA']

### LDA run (gensim LDA and modified mallet wrapper)

In [5]:
# Set parameters
minpc = 0.05 
maxpc = 0.5
alpha = "auto"
beta = "auto"
ntopics = 30

# folder to save model and data files
savefolder = '/Users/gitaepark/Downloads'

# path to mallet bin
mallet_path = '/Users/mallet-2.0.8/bin/mallet'

In [6]:
lda_eval_lib.lda_model.lda_run(tokenized_text, minpc, maxpc, alpha, beta, ntopics, mallet_path, savefolder, gensimpasses = 3, gensimiterations = 3, malletiterations = 100)

 - modelling  gensim_0.05_0.5_30_auto_auto
model saved: /Users/gitaepark/Downloads/gensim_0.05_0.5_30_auto_auto
 - modelling  mallet_0.05_0.5_30_auto_auto
model saved: /Users/gitaepark/Downloads/mallet_0.05_0.5_30_auto_auto

In [8]:
model_path = "/Users/gitaepark/Downloads/gensim_0.05_0.5_30_0.05_0.01"

# Load the stored model
lda_model, textbeforetokenization, tokenized_text, corpus, id2word = lda_eval_lib.util.load_lda_run(model_path)

# lda_model is other gensim.lda object or gensim.mallet object
lda_model.show_topics(num_topics=-1)

[(0,
  '0.012*"clients" + 0.006*"solutions" + 0.004*"merger" + 0.004*"loans" + 0.004*"advertising" + 0.004*"software" + 0.003*"programming" + 0.003*"media" + 0.003*"institutions" + 0.003*"incidents"'),
 (1,
  '0.027*"gas" + 0.008*"commodity" + 0.008*"generation" + 0.008*"oil" + 0.007*"prospects" + 0.007*"utility" + 0.006*"transmission" + 0.005*"nuclear" + 0.005*"electric" + 0.005*"regulators"'),
 (2,
  '0.008*"merger" + 0.006*"opinion" + 0.006*"clients" + 0.006*"representations" + 0.005*"programming" + 0.004*"undertakings" + 0.004*"spin" + 0.004*"care" + 0.004*"solutions" + 0.004*"clinical"'),
 (3,
  '0.028*"loans" + 0.020*"clients" + 0.014*"institutions" + 0.014*"loan" + 0.012*"estate" + 0.012*"banking" + 0.009*"real" + 0.009*"bank" + 0.009*"institution" + 0.009*"libor"'),
 (4,
  '0.005*"vehicles" + 0.004*"gas" + 0.004*"fuel" + 0.003*"shares" + 0.003*"consumers" + 0.003*"incidents" + 0.003*"properties" + 0.003*"retail" + 0.003*"libor" + 0.003*"regulators"'),
 (5,
  '0.006*"raw" + 0.004*"agreement" + 0.003*"manufacture" + 0.003*"preferences" + 0.003*"clients" + 0.003*"brands" + 0.003*"separation" + 0.002*"patents" + 0.002*"consumers" + 0.002*"distributors"'),
 (6,
  '0.005*"libor" + 0.004*"clients" + 0.004*"shares" + 0.003*"merger" + 0.003*"travel" + 0.003*"agreement" + 0.003*"fees" + 0.003*"distributions" + 0.003*"shareholders" + 0.003*"vehicles"'),
 (7,
  '0.004*"segment" + 0.003*"pension" + 0.003*"fair" + 0.003*"consumers" + 0.003*"raw" + 0.003*"locations" + 0.003*"real" + 0.003*"shares" + 0.003*"retail" + 0.002*"libor"'),
 (8,
  '0.007*"shares" + 0.006*"properties" + 0.005*"project" + 0.004*"venture" + 0.004*"pension" + 0.004*"clients" + 0.003*"oil" + 0.003*"surety" + 0.003*"fuel" + 0.003*"shareholders"'),
 (9,
  '0.006*"shareholders" + 0.006*"segment" + 0.005*"shares" + 0.005*"fair" + 0.004*"clients" + 0.003*"diluted" + 0.003*"oil" + 0.003*"drilling" + 0.003*"recognized" + 0.003*"refer"'),
 (10,
  '0.010*"aircraft" + 0.004*"subcontractors" + 0.004*"fuel" + 0.004*"contractor" + 0.004*"budget" + 0.004*"pension" + 0.003*"segment" + 0.003*"air" + 0.003*"carriers" + 0.003*"expirations"'),
 (11,
  '0.015*"clients" + 0.005*"client" + 0.005*"shares" + 0.004*"merger" + 0.004*"loans" + 0.003*"real" + 0.003*"solutions" + 0.003*"bank" + 0.003*"estate" + 0.003*"taxable"'),
 (12,
  '0.029*"oil" + 0.014*"gas" + 0.012*"drilling" + 0.009*"reserves" + 0.006*"shares" + 0.006*"properties" + 0.005*"fuel" + 0.005*"commodity" + 0.004*"rigs" + 0.004*"exploration"'),
 (13,
  '0.003*"clients" + 0.003*"approval" + 0.003*"libor" + 0.003*"medical" + 0.003*"stockholders" + 0.003*"estate" + 0.003*"incidental" + 0.003*"loans" + 0.003*"merger" + 0.003*"commission"'),
 (14,
  '0.011*"gas" + 0.007*"utility" + 0.007*"fuel" + 0.006*"commodity" + 0.005*"electric" + 0.005*"generation" + 0.005*"hazardous" + 0.004*"transmission" + 0.004*"electricity" + 0.004*"properties"'),
 (15,
  '0.017*"vehicles" + 0.009*"vehicle" + 0.006*"shares" + 0.004*"rental" + 0.004*"fuel" + 0.004*"consumers" + 0.004*"fleet" + 0.004*"raw" + 0.003*"properties" + 0.003*"brands"'),
 (16,
  '0.008*"raw" + 0.005*"pension" + 0.004*"automotive" + 0.003*"manufacture" + 0.003*"aircraft" + 0.003*"packaging" + 0.003*"ventures" + 0.003*"venture" + 0.003*"profits" + 0.003*"manufacturers"'),
 (17,
  '0.012*"incorporated" + 0.011*"reference" + 0.005*"annual" + 0.004*"factorsthe" + 0.003*"consumers" + 0.003*"shares" + 0.003*"clients" + 0.003*"loans" + 0.003*"estate" + 0.003*"found"'),
 (18,
  '0.015*"clients" + 0.009*"loans" + 0.006*"curve" + 0.005*"client" + 0.005*"regulators" + 0.004*"travel" + 0.004*"carriers" + 0.004*"aircraft" + 0.004*"collateral" + 0.004*"shares"'),
 (19,
  '0.006*"clients" + 0.004*"raw" + 0.003*"consumers" + 0.003*"default" + 0.003*"class" + 0.003*"cloud" + 0.003*"stockholders" + 0.002*"brand" + 0.002*"agreement" + 0.002*"profits"'),
 (20,
  '0.009*"generation" + 0.008*"electric" + 0.007*"nuclear" + 0.006*"prospects" + 0.006*"utility" + 0.006*"transmission" + 0.005*"gas" + 0.005*"pension" + 0.005*"electricity" + 0.005*"recover"'),
 (21,
  '0.005*"agriculture" + 0.004*"patents" + 0.004*"care" + 0.004*"medical" + 0.004*"manufacture" + 0.003*"raw" + 0.003*"shares" + 0.003*"indemnification" + 0.003*"reimbursement" + 0.003*"research"'),
 (22,
  '0.011*"clinical" + 0.007*"medical" + 0.007*"reimbursement" + 0.006*"care" + 0.006*"clearance" + 0.005*"approval" + 0.005*"healthcare" + 0.004*"devices" + 0.004*"device" + 0.004*"manufacturers"'),
 (23,
  '0.012*"loans" + 0.007*"institutions" + 0.005*"libor" + 0.005*"loan" + 0.004*"shareholders" + 0.003*"bank" + 0.003*"real" + 0.003*"banks" + 0.003*"distributions" + 0.003*"clients"'),
 (24,
  '0.005*"care" + 0.005*"software" + 0.003*"manufacture" + 0.003*"medical" + 0.003*"raw" + 0.003*"license" + 0.003*"patents" + 0.002*"merger" + 0.002*"licenses" + 0.002*"currencies"'),
 (25,
  '0.005*"shares" + 0.005*"loans" + 0.004*"liquidation" + 0.003*"libor" + 0.003*"institutions" + 0.003*"default" + 0.003*"real" + 0.003*"preferred" + 0.003*"raw" + 0.003*"approval"'),
 (26,
  '0.006*"shares" + 0.004*"gas" + 0.004*"pension" + 0.003*"oil" + 0.003*"fuel" + 0.003*"agreement" + 0.003*"properties" + 0.003*"project" + 0.003*"indemnification" + 0.003*"shareholders"'),
 (27,
  '0.014*"beverage" + 0.012*"brands" + 0.010*"packaging" + 0.010*"raw" + 0.009*"consumers" + 0.007*"advertising" + 0.006*"ingredients" + 0.004*"retailers" + 0.004*"commerce" + 0.004*"water"'),
 (28,
  '0.014*"loans" + 0.007*"libor" + 0.007*"real" + 0.006*"institutions" + 0.006*"loan" + 0.006*"banking" + 0.006*"lending" + 0.005*"mortgage" + 0.005*"bank" + 0.004*"estate"'),
 (29,
  '0.075*"gas" + 0.026*"oil" + 0.019*"generation" + 0.015*"electric" + 0.014*"nuclear" + 0.013*"transmission" + 0.010*"water" + 0.010*"drilling" + 0.010*"electricity" + 0.009*"commodity"')]

In [9]:
model_path = "/Users/gitaepark/Downloads/mallet_0.05_0.5_30_0.05_0.01"

# Load the stored model
lda_model, textbeforetokenization, tokenized_text, corpus, id2word = lda_eval_lib.util.load_lda_run(model_path)

# lda_model is other gensim.lda object or gensim.mallet object
lda_model.show_topics(num_topics=-1)

[(0,
  '0.018*"raw" + 0.016*"project" + 0.011*"patents" + 0.010*"venture" + 0.008*"hazardous" + 0.007*"sites" + 0.007*"commodity" + 0.006*"execution" + 0.006*"default" + 0.005*"patent"'),
 (1,
  '0.024*"healthcare" + 0.010*"patents" + 0.010*"agreement" + 0.009*"manufacture" + 0.009*"separation" + 0.008*"patent" + 0.007*"raw" + 0.007*"licenses" + 0.007*"stockholders" + 0.006*"audits"'),
 (2,
  '0.023*"cards" + 0.019*"card" + 0.015*"members" + 0.013*"member" + 0.013*"advertising" + 0.011*"brand" + 0.010*"acceptance" + 0.010*"stations" + 0.009*"travel" + 0.007*"regulators"'),
 (3,
  '0.028*"brands" + 0.020*"water" + 0.019*"consumers" + 0.016*"raw" + 0.013*"beverage" + 0.012*"class" + 0.011*"glass" + 0.011*"retailers" + 0.010*"consumption" + 0.009*"distributors"'),
 (4,
  '0.021*"care" + 0.011*"deterioration" + 0.010*"currencies" + 0.009*"licensing" + 0.008*"medical" + 0.008*"protected" + 0.008*"patient" + 0.007*"interpretations" + 0.006*"taxation" + 0.006*"manufacture"'),
 (5,
  '0.028*"gas" + 0.025*"generation" + 0.023*"electric" + 0.022*"utility" + 0.018*"nuclear" + 0.015*"prospects" + 0.013*"fuel" + 0.013*"transmission" + 0.012*"renewable" + 0.012*"electricity"'),
 (6,
  '0.038*"institutions" + 0.026*"institution" + 0.022*"participate" + 0.020*"title" + 0.019*"iv" + 0.016*"eligibility" + 0.014*"education" + 0.010*"medical" + 0.010*"lose" + 0.010*"aid"'),
 (7,
  '0.017*"yen" + 0.016*"denominated" + 0.012*"instruments" + 0.012*"rating" + 0.010*"derivatives" + 0.009*"derivative" + 0.009*"brand" + 0.008*"premium" + 0.008*"stockholders" + 0.008*"hedging"'),
 (8,
  '0.077*"oil" + 0.069*"gas" + 0.052*"drilling" + 0.028*"rigs" + 0.021*"reserves" + 0.015*"exploration" + 0.013*"crude" + 0.010*"commodity" + 0.010*"offshore" + 0.009*"water"'),
 (9,
  '0.011*"goods" + 0.010*"supplier" + 0.008*"locations" + 0.008*"located" + 0.007*"base" + 0.007*"skilled" + 0.007*"component" + 0.007*"parts" + 0.007*"trading" + 0.007*"resolution"'),
 (10,
  '0.032*"clinical" + 0.021*"medical" + 0.021*"approval" + 0.017*"manufacturers" + 0.016*"devices" + 0.016*"trials" + 0.014*"reimbursement" + 0.013*"drug" + 0.012*"patients" + 0.012*"approved"'),
 (11,
  '0.023*"segment" + 0.016*"note" + 0.014*"dealers" + 0.013*"fair" + 0.012*"compared" + 0.012*"unit" + 0.012*"partially" + 0.011*"pension" + 0.011*"continuing" + 0.011*"recognized"'),
 (12,
  '0.019*"raw" + 0.012*"research" + 0.009*"manufacture" + 0.007*"acceptance" + 0.007*"incidents" + 0.007*"improper" + 0.006*"emerging" + 0.006*"parts" + 0.006*"industrial" + 0.006*"imports"'),
 (13,
  '0.009*"disaster" + 0.006*"quickly" + 0.006*"regulators" + 0.006*"fees" + 0.005*"currencies" + 0.005*"continuity" + 0.005*"country" + 0.005*"properly" + 0.005*"profit" + 0.004*"efficient"'),
 (14,
  '0.045*"loans" + 0.026*"loan" + 0.015*"banking" + 0.015*"real" + 0.015*"bank" + 0.014*"estate" + 0.012*"banks" + 0.012*"collateral" + 0.011*"mortgage" + 0.010*"allowance"'),
 (15,
  '0.035*"software" + 0.016*"solutions" + 0.010*"cloud" + 0.010*"distributors" + 0.007*"licenses" + 0.007*"technical" + 0.007*"incident" + 0.006*"license" + 0.006*"transformation" + 0.006*"consuming"'),
 (16,
  '0.017*"opinion" + 0.017*"taxable" + 0.016*"representations" + 0.014*"merger" + 0.014*"ruling" + 0.012*"distributions" + 0.012*"qualify" + 0.011*"separation" + 0.011*"counsel" + 0.011*"free"'),
 (17,
  '0.037*"properties" + 0.013*"libor" + 0.013*"real" + 0.013*"shares" + 0.012*"lease" + 0.008*"estate" + 0.008*"leases" + 0.007*"executive" + 0.006*"shareholders" + 0.006*"distributions"'),
 (18,
  '0.118*"clients" + 0.039*"client" + 0.019*"solutions" + 0.013*"stockholders" + 0.009*"underwriting" + 0.009*"brokerage" + 0.008*"consulting" + 0.008*"firms" + 0.007*"complete" + 0.007*"publicity"'),
 (19,
  '0.013*"holders" + 0.012*"ii" + 0.011*"directors" + 0.010*"licenses" + 0.010*"covenants" + 0.009*"forum" + 0.009*"assure" + 0.008*"class" + 0.008*"lose" + 0.007*"amended"'),
 (20,
  '0.021*"fuel" + 0.011*"transmission" + 0.010*"digital" + 0.009*"structures" + 0.009*"water" + 0.009*"gas" + 0.009*"coal" + 0.009*"grade" + 0.008*"ways" + 0.008*"respective"'),
 (21,
  '0.011*"care" + 0.009*"clearance" + 0.009*"clinical" + 0.007*"clearances" + 0.007*"monetary" + 0.006*"reimbursement" + 0.006*"collaborative" + 0.005*"ventures" + 0.005*"indemnification" + 0.005*"relationship"'),
 (22,
  '0.047*"shares" + 0.019*"shareholders" + 0.013*"preferred" + 0.013*"termination" + 0.008*"ordinary" + 0.008*"series" + 0.007*"conversion" + 0.007*"principal" + 0.007*"early" + 0.006*"lenders"'),
 (23,
  '0.056*"gas" + 0.025*"generation" + 0.024*"electric" + 0.022*"transmission" + 0.019*"nuclear" + 0.015*"electricity" + 0.015*"consumers" + 0.014*"utility" + 0.011*"plants" + 0.011*"recover"'),
 (24,
  '0.030*"libor" + 0.021*"institutions" + 0.016*"deposits" + 0.009*"fraud" + 0.008*"regulators" + 0.008*"instruments" + 0.008*"confidence" + 0.007*"benchmark" + 0.007*"bank" + 0.007*"counterparties"'),
 (25,
  '0.051*"vehicles" + 0.029*"vehicle" + 0.021*"rental" + 0.018*"fleet" + 0.013*"locations" + 0.009*"truck" + 0.008*"operators" + 0.008*"manufacturers" + 0.008*"fuel" + 0.008*"travel"'),
 (26,
  '0.014*"subcontractors" + 0.014*"profits" + 0.012*"suspension" + 0.012*"aircraft" + 0.011*"backlog" + 0.011*"budget" + 0.010*"contractors" + 0.010*"defense" + 0.009*"segment" + 0.009*"procurement"'),
 (27,
  '0.029*"packaging" + 0.022*"beverage" + 0.018*"consumers" + 0.016*"brands" + 0.015*"ingredients" + 0.010*"publicity" + 0.009*"aluminum" + 0.009*"containers" + 0.009*"retail" + 0.009*"image"'),
 (28,
  '0.048*"aircraft" + 0.028*"travel" + 0.026*"air" + 0.024*"fuel" + 0.023*"airline" + 0.023*"carriers" + 0.019*"airlines" + 0.009*"agreement" + 0.009*"traffic" + 0.007*"fees"'),
 (29,
  '0.031*"pension" + 0.021*"merger" + 0.011*"deferred" + 0.010*"steel" + 0.010*"contributions" + 0.009*"integration" + 0.009*"completion" + 0.009*"defined" + 0.008*"completed" + 0.008*"complete"')]

## model evaluation

In [4]:
model_path = "/Users/gitaepark/Downloads/mallet_0.05_0.5_30_0.05_0.01"

print(f"LDA model loaded from: {model_path}")

a=lda_eval_lib.metrics.IDXtopics2keep(model_path)
print(f"proportion of valid topics: {a}")

b=lda_eval_lib.metrics.diversity(model_path)
print(f"diversity score: {b}")

c=lda_eval_lib.metrics.granularity(model_path)
print(f"granularity score: {c}")

d=lda_eval_lib.metrics.perplexity(model_path)
print(f"perplexity score: {d}")

e=lda_eval_lib.metrics.coherence(model_path)
print(f"coherence score: {e}")

LDA model loaded from: /Users/gitaepark/Downloads/mallet_0.05_0.5_30_0.05_0.01
proportion of valid topics: 1.0
diversity score: 0.7733333333333333
granularity score: 0.6966666666666667
perplexity score: -7.350247503510655
coherence score: 0.5497179415067865

#### GPT assisted tasks (WIT, labelling)

In [4]:
# ChatGPT assisted tasks 
client = lda_eval_lib.util.OpenAI_client()

Enter your API key:  ········

In [5]:
top_n = 5
bottom_n = 0.15
common_n = 20
chunk_size = 3

# Define the model
gpt_model = "gpt-4o"
model_path = "/Users/gitaepark/Downloads/mallet_0.05_0.5_30_0.05_0.01"

lda_eval_lib.gpt_wit.word_intrusion_task(model_path, client, top_n, bottom_n, common_n, chunk_size=10,
                           gpt_model="gpt-4o", temperature=0)

,model_name,task,accuracy
0,mallet_0.05_0.5_30_0.05_0.01,Model Topic ...,0.4

In [6]:
gpt_model = "gpt-4o"
model_path = "/Users/gitaepark/Downloads/mallet_0.05_0.5_30_0.05_0.01"
lda_eval_lib.gpt_labelling.labelling(model_path, client, gpt_model)

Labels checked - overlapping labels identified!
Suggesting new labels...
Done!

,topic,label,rationale,keywords
0,Topic0,Procurement and Project Execution Risks,Emphasizes risks linked with obtaining and han...,"raw, project, patents, venture, hazardous, sit..."
1,Topic1,Healthcare Production and Patenting Risk,Centers on risks related to manufacturing and ...,"healthcare, patents, agreement, manufacture, s..."
2,Topic2,Consumer Payment Systems and Marketing Risks,"The keywords emphasize 'cards', 'card members'...","cards, card, members, member, advertising, bra..."
3,Topic3,Beverage Industry Supply Chain and Consumer Risks,The keywords highlight the beverage industry w...,"brands, water, consumers, raw, beverage, class..."
4,Topic4,Medical Compliance and Currency Risk,Combines risks related to medical compliance a...,"care, deterioration, currencies, licensing, me..."
5,Topic5,Renewable Energy Development Risks,Focuses on risks linked to the development of ...,"gas, generation, electric, utility, nuclear, p..."
6,Topic6,Educational Institution Participation and Fund...,The keywords indicate risks related to educati...,"institutions, institution, participate, title,..."
7,Topic7,Derivative and Hedging Strategy Risks,Emphasizes risks related to the management of ...,"yen, denominated, instruments, rating, derivat..."
8,Topic8,Crude Oil and Gas Extraction Risks,Centers around risks linked to the extraction ...,"oil, gas, drilling, rigs, reserves, exploratio..."
9,Topic9,Component Sourcing and Logistics Vulnerability,Highlights risks arising from sourcing compone...,"goods, supplier, locations, located, base, ski..."
10,Topic10,Medicine and Device Approval Challenges,Focuses on risks linked to gaining approval fo...,"clinical, medical, approval, manufacturers, de..."
11,Topic11,Pension Accountability and Reporting Risks,Stresses the risks connected to pension accoun...,"segment, note, dealers, fair, compared, unit, ..."
12,Topic12,Manufacturing Disruptions and Material Acceptance,Focuses on risks related to the disruption in ...,"raw, research, manufacture, acceptance, incide..."
13,Topic13,Business Continuity and Currency Risks,"Keywords such as disaster, continuity, currenc...","disaster, quickly, fees, regulators, currencie..."
14,Topic14,Real Estate Loan Management Risks,Emphasizes risks associated with the managemen...,"loans, loan, banking, real, bank, estate, bank..."
15,Topic15,Software and Cloud Licensing Technicalities,"The keywords focus on software solutions, clou...","software, solutions, cloud, distributors, lice..."
16,Topic16,Taxable Implications in Corporate Mergers,"This topic revolves around tax opinions, repre...","opinion, taxable, representations, merger, rul..."
17,Topic17,Lease Agreement and Property Ownership Risks,Focuses on risks related to real estate owners...,"properties, libor, real, shares, lease, estate..."
18,Topic18,Client Advisory and Brokerage Operations,This set of keywords pertains to client relati...,"clients, client, solutions, stockholders, unde..."
19,Topic19,Corporate Legal Amendments and Governance Risks,Highlights risks arising from corporate legal ...,"holders, ii, directors, licenses, covenants, f..."
20,Topic20,Logistic and Resource Management in Energy Pro...,Focuses on risks related to resource and logis...,"fuel, transmission, digital, structures, water..."
21,Topic21,Healthcare Approval and Collaboration Risks,Highlights risks connected with approvals and ...,"care, clearance, clinical, clearances, monetar..."
22,Topic22,Equity Financing and Ownership Risks,Focuses on risks linked to shareholder interes...,"shares, shareholders, preferred, termination, ..."
23,Topic23,Energy Supply and Consumer Utility Risks,Highlights risks associated with the supply of...,"gas, generation, electric, transmission, nucle..."
24,Topic24,Financial Integrity and Regulatory Standard Risks,Centered around risks in financial markets rel...,"libor, institutions, deposits, fraud, regulato..."
25,Topic25,Vehicle and Fleet Management Risks,The keywords focus on aspects related to vehic...,"vehicles, vehicle, rental, fleet, locations, t..."
26,Topic26,Subcontractor and Defense Contracting Risks,Focuses on risks related to subcontractor mana...,"subcontractors, profits, suspension, aircraft,..."
27,Topic27,Consumer Goods Packaging and Brand Risks,"Keywords involve packaging, beverages, consume...","packaging, beverage, consumers, brands, ingred..."
28,Topic28,Airline Industry Operational Risks,"The focus on aircraft, travel, fuel, carriers,...","aircraft, travel, air, fuel, airline, carriers..."
29,Topic29,Merger Integration and Pension Management Risks,Highlights risks linked to integration in corp...,"pension, merger, deferred, steel, contribution..."

### Visualization

In [7]:
import pyLDAvis

model_path = "/Users/gitaepark/Downloads/mallet_0.05_0.5_30_0.05_0.01"

pyldavisdata = lda_eval_lib.custom_pyvis.visualize_topics(model_path)

# Apply pyLDAvis
vis_data= pyLDAvis.prepare(**pyldavisdata, R=30, n_jobs = -1, mds='mmds', sort_topics=False)

pyLDAvis.display(vis_data)

/opt/anaconda3/envs/test250122/lib/python3.9/site-packages/pandas/core/internals/blocks.py:393: RuntimeWarning: divide by zero encountered in log
  result = func(self.values, **kwargs)
/opt/anaconda3/envs/test250122/lib/python3.9/site-packages/pandas/core/internals/blocks.py:393: RuntimeWarning: divide by zero encountered in log
  result = func(self.values, **kwargs)
/opt/anaconda3/envs/test250122/lib/python3.9/site-packages/pandas/core/internals/blocks.py:393: RuntimeWarning: divide by zero encountered in log
  result = func(self.values, **kwargs)

In [296]:
# save the result
pyLDAvis.save_html(vis_data, '/Users/gitaepark/Downloads/output_filename.html')